### ISSUE TITLE
Member `year` in the Car class results in JDBC SQL error

### ISSUE THREAD

**Issue by zirahvi** [PacktPublishing/Full-Stack-Development-with-Spring-Boot-and-React#3]
The `Car` class contains member `year`, which causes the SQL statement that creates the table to be invalid:

```
023-01-03 23:56:17.932 DEBUG 81860 --- [  restartedMain] o.h.l.p.build.spi.LoadPlanTreePrinter    : LoadPlan(entity=com.packt.cardatabase.domain.Car)
    - Returns
       - EntityReturnImpl(entity=com.packt.cardatabase.domain.Car, querySpaceUid=<gen:0>, path=com.packt.cardatabase.domain.Car)
    - QuerySpaces
       - EntityQuerySpaceImpl(uid=<gen:0>, entity=com.packt.cardatabase.domain.Car)
          - SQL table alias mapping - car0_
          - alias suffix - 0_
          - suffixed key columns - {id1_0_0_}

2023-01-03 23:56:17.934 DEBUG 81860 --- [  restartedMain] o.h.loader.entity.plan.EntityLoader      : Static select for entity com.packt.cardatabase.domain.Car [NONE]: select car0_.id as id1_0_0_, car0_.brand as brand2_0_0_, car0_.color as color3_0_0_, car0_.model as model4_0_0_, car0_.price as price5_0_0_, car0_.register_number as register6_0_0_, car0_.year as year7_0_0_ from car car0_ where car0_.id=?
2023-01-03 23:56:17.963 DEBUG 81860 --- [  restartedMain] org.hibernate.SQL                        : drop table if exists car CASCADE 
Hibernate: drop table if exists car CASCADE 
2023-01-03 23:56:17.967 DEBUG 81860 --- [  restartedMain] org.hibernate.SQL                        : drop sequence if exists hibernate_sequence
Hibernate: drop sequence if exists hibernate_sequence
2023-01-03 23:56:17.969 DEBUG 81860 --- [  restartedMain] org.hibernate.SQL                        : create sequence hibernate_sequence start with 1 increment by 1
Hibernate: create sequence hibernate_sequence start with 1 increment by 1
2023-01-03 23:56:17.973 DEBUG 81860 --- [  restartedMain] org.hibernate.SQL                        : create table car (id bigint not null, brand varchar(255), color varchar(255), model varchar(255), price integer not null, register_number varchar(255), year integer not null, primary key (id))
Hibernate: create table car (id bigint not null, brand varchar(255), color varchar(255), model varchar(255), price integer not null, register_number varchar(255), year integer not null, primary key (id))
2023-01-03 23:56:17.978  WARN 81860 --- [  restartedMain] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL "create table car (id bigint not null, brand varchar(255), color varchar(255), model varchar(255), price integer not null, register_number varchar(255), year integer not null, primary key (id))" via JDBC Statement

org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table car (id bigint not null, brand varchar(255), color varchar(255), model varchar(255), price integer not null, register_number varchar(255), year integer not null, primary key (id))" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67) ~[hibernate-core-5.6.14.Final.jar:5.6.14.Final]
	...
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.7.7.jar:2.7.7]



Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "create table car (id bigint not null, brand varchar(255), color varchar(255), model varchar(255), price integer not null, register_number varchar(255), [*]year integer not null, primary key (id))"; expected "identifier"; SQL statement:



create table car (id bigint not null, brand varchar(255), color varchar(255), model varchar(255), price integer not null, register_number varchar(255), year integer not null, primary key (id)) [42001-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:502) ~[h2-2.1.214.jar:2.1.214]
	...
	... 39 common frames omitted
```

The asterisk in the error message pinpoints the problem: using reserved word `year` as field name. 

Renaming the member or escaping the name (with `@Column(name=...)`) fixes the issue.

**Comment by juhahinkula** [comment]
Yes, thank you. The year is nowadays illegal word in H2. Using the @Column annotation fixes the issue. You can also rename the property (for example, modelYear) but then remember to use new name in front end part.

**Comment by juhahinkula** [comment]
It was not illegal word in H2 previously. But it should be renamed in the next editions. This is my bad.
Note! There is also one thing that has changed in Security chapters (Chapter 5: Securing and Testing Your Backend) after the book is released. You can find instructions to handle that from 'Pull requests' tab here in Github.

**Comment by zirahvi** [comment]
One more item into the TODO list: The `User` class table name must be escaped as well (in `domain/User.java`).
